  - gather_facts: false
    tasks:
      - docker_service:
            definition:
                services: &id001
                    AC_Cache_Server:
                        image: memcached:1.4.36
                        ports:
                          - 11211:11211
                        volumes:
                          - .:/var/lib/MyVolume
                version: '2'
            state: present
            project_name: demo
        tags:
          - start
      - docker_service:
            definition:
                services: *id001
                version: '2'
            state: present
            project_name: demo
            restarted: true
        tags:
          - restart
      - docker_service:
            definition:
                services: *id001
                version: '2'
            state: present
            project_name: demo
            stopped: true
        tags:
          - stop
      - docker_service:
            definition:
                services: *id001
                version: '2'
            state: absent
            project_name: demo
            remove_volumes: yes
        tags:
          - destroy
      - docker_image:
            state: absent
            force: yes
            name: demo-conductor:latest
        tags: destroy
    hosts: localhost
